### PR TITLE
Updated: CSS stylesheets

### PR DESCRIPTION
**Pull request by GoliathLabs**
Updated README & CSS stylesheets

### CODE REVIEW

**Comment by GoliathLabs** [comment]
We might want to build the new image for Docker Hub

**Comment by psi-4ward** [comment]
lol - automated builds only available in docker-hub pro plans? WTF?

**Comment by GoliathLabs** [comment]
Should I add a Github action for automatic image creation?

**Comment by psi-4ward** [comment]
YES!

**Comment by GoliathLabs** [comment]
You might want to enable github actions so things are being build directly as you merge the PR

**Comment by psi-4ward** [comment]
I think they get enebled when a workflow yaml exists.

**Pull request merged**
